### ISSUE TITLE
django-commands not working

### ISSUE THREAD

**Issue by evaldez89** [vladimirnani/DjangoCommands#32]
Hello everyone

Everytime I try to run a Django command on SBT3 with `ctrl+shift+p > Django: any_command`, the command line shows this error:

`Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 797, in run_
    return self.run()
  File "django-commands in C:\Users\emman\AppData\Roaming\Sublime Text 3\Installed Packages\Django Manage Commands.sublime-package", line 199, in run
  File "django-commands in C:\Users\emman\AppData\Roaming\Sublime Text 3\Installed Packages\Django Manage Commands.sublime-package", line 143, in run_command
  File "django-commands in C:\Users\emman\AppData\Roaming\Sublime Text 3\Installed Packages\Django Manage Commands.sublime-package", line 125, in define_terminal
  File "C:\Program Files\Sublime Text 3\sublime.py", line 1133, in get
    return sublime_api.settings_get(self.settings_id, key)
TypeError: String required`

I uninstalled SBT3 and reinstalled it and all packages but still showing the same behavior. I will appreciate any help.

_PD1:I still can run the commands from CMD but not luck with `ctrl+shift+p > Django: shell` for example._
_PD2: it was working all fine, all I did was add the project to a git server so I can push and pull changes and make branches._

**Comment by rhenter** [comment]
not working for me too

**Comment by evaldez89** [comment]
@rhenter Let me tell you I could not find any help and I was on a hurry, so I installed PyChram from https://plugins.jetbrains.com/pycharm_ce

Give it a try.

**Comment by eduFDiaz** [comment]
Sane here guys!
