### ISSUE TITLE
Not working in windows 10

### ISSUE THREAD

**Issue by ziakhan110** [vladimirnani/DjangoCommands#34]
when i run "Run Server" or any other command nothing happens.
Here is sublime text console output, i am getting this error
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 797, in run_
    return self.run()
  File "django-commands in C:\Users\zia\AppData\Roaming\Sublime Text 3\Installed Packages\Django Manage Commands.sublime-package", line 271, in run
  File "django-commands in C:\Users\zia\AppData\Roaming\Sublime Text 3\Installed Packages\Django Manage Commands.sublime-package", line 143, in run_command
  File "django-commands in C:\Users\zia\AppData\Roaming\Sublime Text 3\Installed Packages\Django Manage Commands.sublime-package", line 125, in define_terminal
  File "C:\Program Files\Sublime Text 3\sublime.py", line 1133, in get
    return sublime_api.settings_get(self.settings_id, key)
TypeError: String required
Also there is no option of Default and User setting it just says "Settings". On my my ubuntu system it is working correctly.

**Comment by ziakhan110** [comment]
please help , i think sublime is not loading this package setting because when i go to settings fro menu both Default and User settings are empty.
![capture](https://cloud.githubusercontent.com/assets/8199129/25172949/faecd9ac-250b-11e7-969c-5f1abc62d951.PNG)

**Comment by sw33n3y** [comment]
Yeah. It sucks. It's an amazing looking package but it isn't very novice/setup friendly at all. A single message for Package control saying "hey. set the env. your good."

Like...to what? I don't user virtualenv. Python3 doesn't use a default ~envs directory if you're using venv.
is virtualenv required??? It just says supported. Everything I've tried doesn't work.

Would have been nice if it linked to this repo. Or, better yet, have something in the settings. I didn't even know if it was supposed to be json I was so lost. lol.

You need to populate it with this and then set it to your system. 

{
    // Path to python interpreter
    // It is being overriden when set_virutal_env command is invoked.
    "python_bin": null,
    // Force finding manage.py in this directory
    "django_project_root" : null,
    // List of paths where to find virtual environments
    "python_virtualenv_paths": [
         "~\\.virtualenvs", // virtualenvwrapper
        "~\\.venv", // venv.bash https://github.com/wuub/venv
    ],
    // Python executable version (in case of using the default)
    "python_version": 3,
    // Run server host
    "server_host": "127.0.0.1",
    // Run server in port
    "server_port": "8000",
    // Linux only: define your preferred terminal emulator
    "linux_terminal": "x-terminal-emulator",
    // Mac OSX only: define your preferred_terminal_emulator
    "osx_terminal": "Terminal",
    // Per project setting "python_interpreter" overrides "python_bin"
    "project_override": true,
    // Open browser pointint to root url after runserver command
    "browser_after_runserver": false,
    // Example Settings THIS SETTINGS ARE PER PROJECT FILE inside the settings 
        "server_custom_command": 
        {
         "command": "gunicorn",
         "args":
         [
             "example.wsgi:application",
             "--bind",
             "0.0.0.0:8000",
             "--workers=3",
             "--log-file=-"
         ]
        },
        //or
        "server_custom_command":
        {
            "command": "uwsgi",
            "args":
            [
                "--chdir=/path/to/your/project/",
                "--module=example.wsgi:application",
                "--env",
                "DJANGO_SETTINGS_MODULE=example.settings",
                "--socket=example.com:8000",
                "--processes=5",
                "--uid=1000",
                "--gid=2000",
                "--harakiri=20",
                "--max-requests=5000",
                "--vacuum"
            ],
            "run_with_python": false
        },
        //or
        "server_custom_command":
        {
            "command": "your_script.sh",
            "args":
            [],
            "run_with_python": false
        }
}


But good luck with that. I still haven't seen the glorious project folder popup with "django: add project"

**Comment by nathanjr** [comment]
Hi,

I had the same issue in Windows 10 but expect that it would occur for any version of Windows.

I'm just new to Django Commands but it looks like it would have started happening with a recent commit with changes to define_terminal() in django-commands.py.

Previously when PLATFORM = 'Windows' it wouldn't have tried to read the settings to define TERMINAL as this isn't required for Windows.

I've made a fix on a fork of the repository to skip this TERMINAL definition for Windows and have created a Pull Request for this repository.

Hope this helps.

Cheers,

Nathan.
