### ISSUE TITLE
terminal emulator not found: Terminal Using fallback instead

### ISSUE THREAD

**Issue by daimon99** [vladimirnani/DjangoCommands#39]
When run 'django run server' or other django commands, sublime prompts:` terminal emulator not found: Terminal
Using fallback instead.`
then look into console, some error here:

```
- Django: Command is : None
Exception in thread Thread-12:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "django-commands in /Users/daiyue/Library/Application Support/Sublime Text 3/Installed Packages/Django Manage Commands.sublime-package", line 184, in run
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1343, in _execute_child
TypeError: 'NoneType' object is not iterable

```

**Comment by eduFDiaz** [comment]
Same here!

**Comment by thepieuvre** [comment]
Same error with Sublime Text 3 on macOS 10.13. I tried Terminal and iTerm2 both failed.
